name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
        check-bats-version:
                runs-on: docker-desktop
                steps:
                        - uses: actions/checkout@v4
                        - uses: actions/setup-node@v3
                          with:
                                  node-verison: '14'
                        - run: npm install -g bats
                        - run: bats -v

